inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'farkle.gemspec'
    - 'spec/**/*'

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/MutableConstant:
  Enabled: false
