language: ruby
before_install: gem install bundler -v 1.11.2
bundler: cache
rvm:
  - 2.1
  - 2.2
  - 2.3.0
script: bundle exec rake 
branches:
  only:
    - master
addons:
  code_climate:
    repo_token:
      secure: "qW5Kv8qCTfUwqbfm+GKpndfoduhRa+Tam78nyeTHsxhP35i7SsQs7utZOWKO6ADlxiZsD6WRb4LuUB3lPmcI3nfHsuuw3LgmURsWFHAMLPjhro7Tbt7YGVGAnVmEwnv7LFK739bhkkuVQqg0eahZvkVpXv0GNbfnR5a8CxtnAOir6l3cnkmY3p1De6Tn4BGv46OOfxFMuwbpOI1kLwWyPLAq1k+wGyN6MXXs36Lt68kKfZBhh7S5dexwW80o4eh+q8P+pnPCS2RJED+1mJrrwAQxJJuS1QE52zG0xpAHwJ9odAJoVx3Jvy7n61D9pog/HMQ7LfhMKYviqS6u6FmRb2DHT9Uu+1bVHckTPxToBuT6SFfX+aZyYmYYa2DMxdSxGx4vPYsftHjLBUJEQ/IohOLX9/fNp9reSibEh/Y1GhiI8sj8OzL3z2UOKNu4A3IEcuOSEV1EX0yEIUCN3wvA+EMWPIVdwJciDgzSZlRZGs8oy1+YwqbUznGlZ0Oxwf3ijNpFMyATINrPLxPDXEmapJNwvmV2rzYd9SOKszZjpsOwlONCrrg+bJXDrw13nXnvKJlnmTN6jS5H5g8US12xZCw1VgSyYQFXuWlMfLq/8P6R5/Rm4HFdfaLG0lxPpnKqvZwNOaHI3Os2TOvlqHyZvsdHJ2KegYxVi9uP0TGE5jA="
